### ISSUE TITLE
PLZ

### ISSUE THREAD

**Issue by btholt** [kentcdodds/react-ava-workshop#1]
Please post this as soon as humanly possible. I can haz?

**Comment by kentcdodds** [comment]
Sure thing @btholt! I'll be giving this workshop at PayPal on the 12th. I plan to record it :+1:

**Comment by kentcdodds** [comment]
Also, it's flattering that you care :-)

**Comment by btholt** [comment]
Oh that'd be great if you recorded it. I'm really interested in ava.

I'll consider this issue solved then! :grin:

**Comment by kentcdodds** [comment]
Hey man,
I still plan to record this tomorrow, but I don't know if there's going to be much you'll get out of the recording that you can't get out of the repo. It's all ready to go :+1: :tiger: 

Great seeing you this week!

**Comment by btholt** [comment]
Likewise great to see you! And I'm _very_ excited to dig into this.
