### ISSUE TITLE
npm run cover fails

### ISSUE THREAD

**Issue by coryhouse** [kentcdodds/react-ava-workshop#6]
| => npm run cover

> react-ava-workshop@1.0.0 cover /Users/coryhouse/Desktop/projects/react-ava-workshop
> nyc npm run test
> 
> react-ava-workshop@1.0.0 test /Users/coryhouse/Desktop/projects/react-ava-workshop
> ava "app/*_/_.test.js" --verbose

  ✔ store › Customers › customers should start with empty
  ✔ store › Customers › setting customers and getting them
  ✔ containers › CustomerList › Renders no customers and add button
  ✔ components › Toggle › toggle--off class applied by default
  ✔ store › Customers › subscribing to the store
  ✔ components › Toggle › toggle--on class applied when initialToggledOn specified to true
  ✔ containers › CustomerList › Renders customers and add button
  ✔ containers › CustomerList › Responds to store updates
  ✔ components › Toggle › invokes the onToggle prop when clicked
  ✔ containers › CustomerList › unsubscribes when unmounted

  10 tests passed

/Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/report/html.js:241
            text = structuredText[startLine].text;
                                            ^

TypeError: Cannot read property 'text' of undefined
    at /Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/report/html.js:241:45
    at Array.forEach (native)
    at annotateFunctions (/Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/report/html.js:224:26)
    at HtmlReport.Report.mix.writeDetailPage (/Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/report/html.js:427:9)
    at /Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/coryhouse/Desktop/projects/react-ava-workshop/node_modules/istanbul/lib/report/html.js:482:23)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/coryhouse/.nvm/versions/node/v5.6.0/bin/node" "/Users/coryhouse/.nvm/versions/node/v5.6.0/bin/npm" "run" "cover"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! react-ava-workshop@1.0.0 cover: `nyc npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-ava-workshop@1.0.0 cover script 'nyc npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-ava-workshop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nyc npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-ava-workshop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-ava-workshop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/coryhouse/Desktop/projects/react-ava-workshop/npm-debug.log

**Comment by coryhouse** [comment]
OSX El Capitan, npm 3.6.0, Node 5.6.0

**Comment by kentcdodds** [comment]
:sweat_smile: hee hee, you were too fast! Try to install `nyc@next` :-) That should fix it for you. This should be released soon!

**Comment by kentcdodds** [comment]
By the way, thanks for running through this. Please please please leave feedback (and PRs) to improve this!

**Comment by coryhouse** [comment]
This is awesome! Superb timing since exactly what I was looking for today! Great work!

**Comment by kentcdodds** [comment]
![high-five-explosion-JQNM4AgN7lFUA](https://camo.githubusercontent.com/2dc06bd49a32a471a2522ce5ca6504fc06f83e4f/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a514e4d3441674e376c4655412f67697068792e676966)

**Comment by coryhouse** [comment]
Boom. @next fixed it. Thanks Kent!

**Comment by kentcdodds** [comment]
Sweet! This should be released sometime this week [I'm told](https://github.com/bcoe/nyc/pull/218#issuecomment-205653975) :-)
