### ISSUE TITLE
Did you consider cheerio?

### ISSUE THREAD

**Issue by coryhouse** [kentcdodds/react-ava-workshop#7]
I've enjoyed testing with [cheerio](https://github.com/cheeriojs/cheerio) instead of jsdom. It's fast and offers a jQuery-like selector engine. Just curious if there's a reason you prefer jsdom.

**Comment by kentcdodds** [comment]
I wanted to do as little abstraction as possible for this workshop. I haven't used cheerio or enzyme yet. Definitely open to a PR (feel free to start small) that demonstrates how the tests could have been improved with an abstraction :-)

**Comment by coryhouse** [comment]
Great point. I didn't consider that it's indeed an extra layer which could hamper learning. Sadly, my DOM querying skills are feeling rusty.

**Comment by kentcdodds** [comment]
> my DOM querying skills are feeling rusty.

Luckily you only really need those skills when you're interviewing :stuck_out_tongue_winking_eye:
